zh-Hans:
  site:
    title: dyf189的博客

theme:
  default: style-dark

user:
  name: dyf189
  first_name: 的博客
  last_name: dyf189
  avatar: https://avatars.githubusercontent.com/u/100421701?v=4
  describe: 一个网站。

sidebar:
  social: # 社交地址
    - name: github
      icon: fab fa-github
      url: https://github.com/dyf189
  info: # 个人信息
    - key: 邮箱
      val: gitdyf189@outlook.com

footer:
  custom_text: <a href="https://dyf189.github.io">dyf189的博客</a> © 2026 by <a href="https://github.com/dyf189">dyf189</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>

top_bars:
  - title: 主页
    url: /
  - title: 分类
    url: /categories/
  - title: 归档
    url: /archives/
    noswup: true
  - title: 关于
    url: /about/
    noswup: true
  - title: 友情链接
    url: /links/

creative_commons:
  license: by-nc-sa
  language: deed.zh-hans
  post: false
  clipboard: false

notice_outdate:
  enable: true
  style: flat
  limit_day: 365
  position: top

comment:
  giscus:
    enable: true
    repo: dyf189/dyf189.github.io
    repo-id: R_kgDORKxyLg
    category: Announcements
    category-id: DIC_kwDORKxyLs4C2EnQ
    mapping: pathname
    reactions-enabled: 1
    emit-metadata: 0
    lang: zh-CN
    theme: 
      light: light
      dark: dark

links:
  - name: USFrameTeam
    url: //www.usframeteam.top/
    image: //www.usframeteam.top/static/pictures/USFLogo.png
    desc: Minecraft基岩版插件USF开发团队

links_info:
  name:  dyf189的博客
  url: https://dyf189.github.io/
  describe: 小站
  rule_text: 暂不接受友链申请。
